### ISSUE TITLE
Not possible to pass args or options

### ISSUE THREAD

**Issue by st7xxx** [DedInc/pyanty#21]
I am trying to pass a extension to the application but neither the proper args for pyppeteer or the options for selenium dont work   

args: [
    '--disable-extensions-except=/path/to/extension/',
    '--load-extension=/path/to/extension/',
  ]
  
  options.add_extension('./exampleOfExtensionDownloadedToFolder.crx')

**Comment by DedInc** [comment]
Extensions in Dolphin Any are added differently, the update will have

**Comment by DedInc** [comment]
Fixed
