### ISSUE TITLE
Running undetectable for CDP bot detection?

### ISSUE THREAD

**Issue by neestzjov** [DedInc/pyanty#24]
How to run undetectable for CDP detection such as this service? https://www.browserscan.net/bot-detection

The rest of detections are not positive as dolphin does the job but when it comes to controlling the browser CDP is detected

**Comment by DedInc** [comment]
https://github.com/DedInc/pystealth/

**Comment by neestzjov** [comment]
> https://github.com/DedInc/pystealth/

Can I also integrate this module with dolphin profiles?
