### ISSUE TITLE
Title: KeyError: 'automation' after latest Dolphin Anty update

### ISSUE THREAD

**Issue by BrunoNRS** [DedInc/pyanty#25]
After updating to the latest version of Dolphin Anty, I encountered a KeyError: 'automation' when using pyanty to create profiles with a proxy. This error was not present before the update. Below is the traceback for the error:

Error Traceback:

```
Traceback (most recent call last):
  File "D:\Software\Projects\dolphin_project\main.py", line 24, in <module>
    main()
  File "D:\Software\Projects\dolphin_project\main.py", line 14, in main
    profile_id, port = create_profile_with_proxy(profile_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\Projects\dolphin_project\profile_manager.py", line 44, in create_profile_with_proxy
    port = profile_response['automation']['port']
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'automation'

```
This error started occurring immediately after updating to the latest Dolphin Anty version. The same code was working correctly before the update.

**Comment by DedInc** [comment]
After the updates it really became more difficult to use it
