### ISSUE TITLE
github rate-limits

### ISSUE THREAD

**Issue by DartanyanPatek** [DedInc/pyanty#26]
'User-Agent': f'dolphin_anty_{self._get_latest_release()}_Windows_NT',
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyanty\api.py", line 265, in _get_latest_release
    return requests.get('https://api.github.com/repos/dolphinrucom/anty-releases/releases/latest').json()['name']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'


Github response:
{"message":"API rate limit exceeded for 94.***.**.**. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

**Comment by DedInc** [comment]
just wait
